Catch LinkageError to fix loci_tools with ImageJ
The switch from throwable to ReflectiveOperationException does not catch
java.lang.NoClassDefFoundError thrown by Log4jTools.